project:
  type: website
  output-dir: docs

website:
  title: "Curiosity | Imagination | Rigor"
  description: "Blog of Souvik Sarkar on Mathematics, Statistcs, and Computer Science."
  favicon: profile.png
  twitter-card: true
  site-url: https://sounix000.github.io
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - souvik_sarkar.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml
  page-footer: 
    center: "Copyright 2024, Souvik Sarkar"
    border: true
    background: light
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

comments:
  giscus: 
    repo: sounix000/sounix000.github.io
    repo-id: R_kgDOLgR5mA
    category: Announcements
    category-id: DIC_kwDOLgR5mM4CeEwB
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: top
    theme: light
    language: en





