project:
  type: website
  output-dir: docs

website:
  title: "Curiosity | Imagination | Rigor"
  site-url: https://sounix000.github.io
  description: "Technical blog of Souvik Sarkar"
  comments:
    giscus:
      repo: sounix000/sounix000.github.io
      repo-id: R_kgDONbIV7g
      category: Announcements
      category-id: DIC_kwDONbIV7s4ClEYf
      mapping: pathname
      reactions-enabled: true
      input-position: bottom
      theme: preferred_color_scheme
      language: en
        
  navbar:
    right:
      - souvik-sarkar.qmd
      - icon: github
        href: https://github.com/sounix000
      - icon: linkedin
        href: https://linkedin.com/in/sounix000
      - icon: twitter
        href: https://twitter.com/sounix000
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



