project:
  type: website
  output-dir: docs

website:
  title: "Curiosity | Imagination | Rigor"
  site-url: https://sounix000.github.io
  description: "Technical blog of Souvik Sarkar"
  navbar:
    right:
      - souvik-sarkar.qmd
      - icon: github
        href: https://github.com/sounix000
      - icon: linkedin
        href: https://linkedin.com/in/sounix000
      - icon: twitter
        href: https://twitter.com/sounix000
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



